apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: dev
  app.kubernetes.io/managed-by: kustomize
namespace: dev

images:
  - name: nginx:1.14.2
    newName: nginx
    newTag: 1.14.2

resources:
- ../../base

patchesStrategicMerge:
- web.yaml
- ingress.yaml
