apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: dev
  app.kubernetes.io/managed-by: kustomize
namespace: dev

resources:
- ../../base

patchesStrategicMerge:
- ingress.yaml
