##################################################################################################
# WebApp Color
##################################################################################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-color
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: webapp-color
        env:
        - name: APP_COLOR
          value: "green"
          # supported color: ["red", "green", "blue", "blue2", "darkblue", "pink"]
