## dev
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-dev
  namespace: argocd
  labels:
    environment: dev
spec:
  project: gitops-demo
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    kustomize:
    path: deploy/overlays/dev
    repoURL: https://github.com/tarosaiba/argocd-on-rancher-desktop.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true

## stg
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-stg
  namespace: argocd
  labels:
    environment: stg
spec:
  project: gitops-demo
  destination:
    namespace: stg
    server: https://kubernetes.default.svc
  source:
    kustomize:
    path: deploy/overlays/stg
    repoURL: https://github.com/tarosaiba/argocd-on-rancher-desktop.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true

## prod
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-prod
  namespace: argocd
  labels:
    environment: prod
spec:
  project: gitops-demo
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  source:
    kustomize:
    path: deploy/overlays/prod
    repoURL: https://github.com/tarosaiba/argocd-on-rancher-desktop.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true

## env01
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-env01
  namespace: argocd
  labels:
    environment: env01
spec:
  project: gitops-demo
  destination:
    namespace: env01
    server: https://kubernetes.default.svc
  source:
    kustomize:
    path: deploy/overlays/env01
    repoURL: https://github.com/tarosaiba/argocd-on-rancher-desktop.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-env02
  namespace: argocd
  labels:
    environment: env02
spec:
  project: gitops-demo
  destination:
    namespace: env02
    server: https://kubernetes.default.svc
  source:
    kustomize:
    path: deploy/overlays/env02
    repoURL: https://github.com/tarosaiba/argocd-on-rancher-desktop.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-env03
  namespace: argocd
  labels:
    environment: env03
spec:
  project: gitops-demo
  destination:
    namespace: env03
    server: https://kubernetes.default.svc
  source:
    kustomize:
    path: deploy/overlays/env03
    repoURL: https://github.com/tarosaiba/argocd-on-rancher-desktop.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
