## dev
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-dev
  namespace: argocd
  labels:
    environment: dev
spec:
  project: gitops-demo
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    kustomize:
    path: deploy/overlays/dev
    repoURL: https://github.com/tarosaiba/gitops-demo-local.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true

## env01
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-env01
  namespace: argocd
  labels:
    environment: env01
spec:
  project: gitops-demo
  destination:
    namespace: env01
    server: https://kubernetes.default.svc
  source:
    kustomize:
    path: deploy/overlays/env01
    repoURL: https://github.com/tarosaiba/gitops-demo-local.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-env02
  namespace: argocd
  labels:
    environment: env02
spec:
  project: gitops-demo
  destination:
    namespace: env02
    server: https://kubernetes.default.svc
  source:
    kustomize:
    path: deploy/overlays/env02
    repoURL: https://github.com/tarosaiba/gitops-demo-local.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
