---
apiVersion: v1
kind: Namespace
metadata:
  name: dev

---
apiVersion: v1
kind: Namespace
metadata:
  name: stg

---
apiVersion: v1
kind: Namespace
metadata:
  name: prod

---
apiVersion: v1
kind: Namespace
metadata:
  name: env01

---
apiVersion: v1
kind: Namespace
metadata:
  name: env02

---
apiVersion: v1
kind: Namespace
metadata:
  name: env03
