apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/env: env01
  app.kubernetes.io/managed-by: kustomize
namespace: env01

resources:
- ../../base

patchesStrategicMerge:
- ingress.yaml
- webapp-color.yaml
